version: '3.8'

services:
  # Base de Datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: macuin_db
    restart: always
    environment:
      POSTGRES_USER: macuin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: DB_macuin
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - macuin_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U macuin -d DB_macuin" ]
      interval: 5s
      retries: 5
      timeout: 5s

  # API FastAPI
  api:
    build: ./API
    container_name: macuin_api
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DATABASE_URL=postgresql://macuin:123456@postgres:5432/DB_macuin
    volumes:
      - ./API:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - macuin_network
    restart: unless-stopped

  # Aplicación Flask
  flask:
    build: ./Flask
    container_name: macuin_flask
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - FLASK_PORT=5001
    volumes:
      - ./Flask:/app
    command: gunicorn --reload -w 4 --threads 2 -b 0.0.0.0:5001 "main:create_app()"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - macuin_network
    restart: unless-stopped

  # Aplicación Laravel
  laravel:
    build: ./Laravel
    container_name: macuin_laravel
    ports:
      - "8003:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8003
    volumes:
      - ./Laravel:/var/www/html
      - ./Laravel/php-dev.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache-dev.ini
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - macuin_network
    restart: unless-stopped

networks:
  macuin_network:
    driver: bridge

volumes:
  postgres_data:
