version: '3.8'

services:
  # API FastAPI
  api:
    build: ./API
    container_name: macuin_api
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    volumes:
      - ./API:/app
    networks:
      - macuin_network
    restart: unless-stopped

  # Aplicación Flask
  flask:
    build: ./Flask
    container_name: macuin_flask
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_PORT=5000
    volumes:
      - ./Flask:/app
    command: gunicorn --reload -w 4 --threads 2 -b 0.0.0.0:5000 "main:create_app()"
    networks:
      - macuin_network
    restart: unless-stopped

  # Aplicación Laravel
  laravel:
    build: ./Laravel
    container_name: macuin_laravel
    ports:
      - "8002:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8002
    volumes:
      - ./Laravel:/var/www/html
      - ./Laravel/php-dev.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache-dev.ini
    networks:
      - macuin_network
    restart: unless-stopped

networks:
  macuin_network:
    driver: bridge
