from .direccion import DireccionBase
from .rol import RolBase
from .usuario import UsuarioBase
from .categoria import CategoriaBase
from .marca import MarcaBase
from .autoparte import AutoparteBase
from .inventario import InventarioBase
from .estatus_pedido import EstatusPedidoBase
from .pedido import PedidoBase
from .detalle_pedido import DetallePedidoBase
